# Site settings
title: MonkeyAndres # site title
description: >- # site description
  I'm a self-taught developer that enjoys problem-solving and continuously learning. I have ample experience on frontend and backend development.
lang: en-US # default lang
timezone: Europe/Madrid # set your timezone
image: # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/monkeyandres/monkeyandres.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Andres Martin Angulo # author name
  bio: >- # tell to the world
    I'm a self-taught developer that enjoys problem-solving and continuously learning. I have ample experience on frontend and backend development.
  username: monkeyandres # general username
  github: monkeyandres # github username
  twitter: # twitter username
  facebook: # facebook username
  email: monkeyandres@protonmail.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://monkeyandres.com" #
baseurl:
permalink: /post/:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  default_front_matter:
    posts:
      description:
      pin: false
      tags: []
    drafts:
      description:
      tags: []

# Homepage limit posts
number_of_posts: 6

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
