# Site settings
title: MonkeyAndres # site title
description: >- # site description
  Personal site of Andres Martin Angulo. Software Developer. Minimalist. Calisthenics Athlete. Homecook.
lang: en-US # default lang
timezone: Europe/Madrid # set your timezone
image: # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/monkeyandres/monkeyandres.github.io # site repo [optional]
mode: # default theme "dark" | "light"

# Profile settings
author:
  name: Andres Martin Angulo # author name
  bio: >- # tell to the world
    Discovering what it means to be alive. <br />
    Trying to make the world a better place.
  username: monkeyandres # general username
  telegram: monkeyandres
  github: monkeyandres # github username
  linkedin: monkeyandres # linkedin username
  twitter: # twitter username
  facebook: # facebook username
  email: monkeyandres@protonmail.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://monkeyandres.com" #
baseurl:
permalink: /post/:title/
google_analytics: G-WREVYFGQ99 # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  parse_block_html: true # For TOC

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  default_front_matter:
    posts:
      description:
      pin: false
      tags: []
    drafts:
      description:
      pin: false
      tags: []

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
